from typing import Any, Callable, Iterable

class ConsumerRebalanceListener:
    async def on_partitions_assigned(self, assigned: Any) -> None: ...
    async def on_partitions_revoked(self, revoked: Any) -> None: ...

class AIOKafkaConsumer:
    def __init__(
        self,
        *topics: str,
        bootstrap_servers: str,
        group_id: str | None = ...,
        enable_auto_commit: bool = ...,
        auto_offset_reset: str = ...,
        value_deserializer: Callable[[bytes], Any] | None = ...,
    ) -> None: ...
    def subscribe(
        self, topics: Iterable[str], listener: ConsumerRebalanceListener | None = ...
    ) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def seek_to_beginning(self, *assigned: Any) -> None: ...
    async def getmany(
        self, timeout_ms: int = ..., max_records: int | None = ...
    ) -> dict[Any, list[Any]]: ...
